services:
    api:
        image: node:22
        working_dir: /var/api
        volumes:
            - ..:/var/api:cached
        # command: ["sh", "-c", "npm run start:dev"]
        command: sleep infinity
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: development
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_DATABASE: user_hierarchy
        depends_on:
            - postgres
        stdin_open: true
        tty: true

    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: user_hierarchy
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5452:5432"

volumes:
    db_data:
