services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/api
        volumes:
            - ..:/var/api:cached
            - node_modules:/var/api/node_modules
        # command: ["sh", "-c", "npm run start:dev"]
        command: sleep infinity
        ports:
            - "3000:3000"
            - "9229:9229" # Debug port
        environment:
            NODE_ENV: development
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_DATABASE: user_hierarchy
        depends_on:
            - postgres
        stdin_open: true
        tty: true

    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: user_hierarchy
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5452:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
    node_modules:
